// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzKrR2dH8JVVYnw4dYeUgKSFNbvDydpU',
    appId: '1:372366097199:web:e8f3774bcb631db15bbfda',
    messagingSenderId: '372366097199',
    projectId: 'isgarbage-a1725',
    authDomain: 'isgarbage-a1725.firebaseapp.com',
    storageBucket: 'isgarbage-a1725.appspot.com',
    measurementId: 'G-MJ5K0KDYQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Iq-hHZokMoHUD2YlNqoMDefrF70lChw',
    appId: '1:372366097199:android:420ee5136fe6160c5bbfda',
    messagingSenderId: '372366097199',
    projectId: 'isgarbage-a1725',
    storageBucket: 'isgarbage-a1725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRjuTDVkprpe5zlDErIKi6iHNrsDzlFU',
    appId: '1:372366097199:ios:01d01f27cca9b8655bbfda',
    messagingSenderId: '372366097199',
    projectId: 'isgarbage-a1725',
    storageBucket: 'isgarbage-a1725.appspot.com',
    iosClientId: '372366097199-jtttms9el5gjuego61bjggjt36srnorh.apps.googleusercontent.com',
    iosBundleId: 'com.example.testmasp',
  );
}
